"""
Medical Facility Template
Specialized cleaning for healthcare facilities
"""

from .shared_sections import get_universal_property_section


def get_medical_template():
    """Get the Medical Facility template configuration"""
    return {
        "template_id": "medical",
        "name": "Medical Facility",
        "description": "Specialized cleaning for healthcare facilities.",
        "image": "https://res.cloudinary.com/dxqum9ywx/image/upload/v1768087509/medical_facility_xqzwjp.jpg",
        "color": "#1a1a1a",
        "template_data": {
            "sections": [
                {
                    "id": "client-info",
                    "title": "Contact Information",
                    "description": "Primary contact details for this facility.",
                    "fields": [
                        {
                            "id": "contactName",
                            "label": "Primary contact name",
                            "type": "text",
                            "placeholder": "Dr. John Smith",
                            "required": True,
                        },
                        {
                            "id": "businessName",
                            "label": "Facility / Practice name",
                            "type": "text",
                            "placeholder": "Smith Family Medicine",
                            "required": True,
                        },
                        {
                            "id": "email",
                            "label": "Email address",
                            "type": "email",
                            "placeholder": "admin@smithfamilymedicine.com",
                            "required": True,
                        },
                        {
                            "id": "phone",
                            "label": "Phone number",
                            "type": "tel",
                            "placeholder": "(555) 123-4567",
                            "required": True,
                        },
                        {
                            "id": "serviceAddress",
                            "label": "Facility address",
                            "type": "textarea",
                            "placeholder": "123 Medical Plaza, Suite 200, City, State ZIP",
                            "required": True,
                        },
                    ],
                },
                get_universal_property_section(),
                {
                    "id": "medical-specific",
                    "title": "Facility Details",
                    "description": "Tell us about your healthcare facility.",
                    "fields": [
                        {
                            "id": "facilityType",
                            "label": "Primary facility type",
                            "type": "select",
                            "options": [
                                "General practice",
                                "Dental office",
                                "Specialty clinic",
                                "Urgent care",
                                "Surgical center",
                                "Diagnostic center",
                                "Physical therapy",
                                "Other",
                            ],
                            "required": True,
                        },
                        {
                            "id": "facilitySubtype",
                            "label": "Facility subtype (if applicable)",
                            "type": "text",
                            "placeholder": "e.g., Pediatrics, Cardiology, Orthopedics",
                            "required": False,
                        },
                        {
                            "id": "numberOfExamRooms",
                            "label": "Number of exam rooms",
                            "type": "number",
                            "placeholder": "5",
                            "required": True,
                        },
                        {
                            "id": "areasServiced",
                            "label": "Areas requiring cleaning",
                            "type": "multiselect",
                            "options": [
                                "Exam rooms",
                                "Procedure rooms",
                                "Lab areas",
                                "Waiting room",
                                "Reception area",
                                "Staff break room",
                                "Administrative offices",
                                "Storage areas",
                            ],
                            "required": True,
                            "hint": "Select all that apply",
                        },
                        {
                            "id": "numberOfRestrooms",
                            "label": "Number of restrooms",
                            "type": "number",
                            "placeholder": "3",
                            "required": True,
                        },
                        {
                            "id": "hasRestrictedAreas",
                            "label": "Are there restricted access areas?",
                            "type": "radio",
                            "options": ["Yes", "No"],
                            "required": True,
                        },
                        {
                            "id": "restrictedAreasDetails",
                            "label": "Restricted areas details",
                            "type": "textarea",
                            "placeholder": "Describe restricted areas and access requirements",
                            "required": False,
                            "conditionalOn": {
                                "fieldId": "hasRestrictedAreas",
                                "value": "Yes",
                            },
                        },
                    ],
                },
                {
                    "id": "cleaning-scope",
                    "title": "Cleaning Requirements",
                    "description": "Specify your cleaning needs and schedule.",
                    "fields": [
                        {
                            "id": "cleaningFrequency",
                            "label": "Cleaning frequency",
                            "type": "select",
                            "options": [
                                "Daily",
                                "5 days per week",
                                "3 days per week",
                                "Weekly",
                                "Bi-weekly",
                                "Custom schedule",
                            ],
                            "required": True,
                        },
                        {
                            "id": "visitsPerWeek",
                            "label": "Number of visits per week",
                            "type": "number",
                            "placeholder": "3",
                            "required": False,
                            "conditionalOn": {
                                "fieldId": "cleaningFrequency",
                                "value": "Custom schedule",
                            },
                        },
                        {
                            "id": "operatingHours",
                            "label": "Facility operating hours",
                            "type": "text",
                            "placeholder": "e.g., Monday-Friday 8am-6pm",
                            "required": True,
                            "hint": "When is the facility open to patients?",
                        },
                        {
                            "id": "cleaningWindow",
                            "label": "Preferred cleaning window",
                            "type": "select",
                            "options": [
                                "After hours (evenings)",
                                "Early morning (before opening)",
                                "During business hours",
                                "Weekends only",
                                "Flexible",
                            ],
                            "required": True,
                        },
                        {
                            "id": "requiresMedicalGradeDisinfection",
                            "label": "Medical-grade disinfection required?",
                            "type": "radio",
                            "options": ["Yes", "No"],
                            "required": True,
                        },
                        {
                            "id": "approvedDisinfectants",
                            "label": "Specific disinfectant requirements",
                            "type": "textarea",
                            "placeholder": "List any required or approved disinfectants (e.g., EPA-registered, hospital-grade)",
                            "required": False,
                            "hint": "Leave blank if no specific requirements",
                        },
                        {
                            "id": "biohazardWork",
                            "label": "Does cleaning involve biohazard waste handling?",
                            "type": "radio",
                            "options": ["Yes", "No"],
                            "required": True,
                            "hint": "Biohazard work requires manual review and specialized protocols",
                        },
                    ],
                },
                {
                    "id": "access-and-operations",
                    "title": "Access & Operations",
                    "description": "Facility access and operational details.",
                    "fields": [
                        {
                            "id": "accessMethod",
                            "label": "Access method",
                            "type": "select",
                            "options": [
                                "Key provided",
                                "Access code",
                                "On-site staff present",
                                "Building management",
                                "Other",
                            ],
                            "required": True,
                        },
                        {
                            "id": "alarmSystem",
                            "label": "Alarm system present?",
                            "type": "radio",
                            "options": ["Yes", "No"],
                            "required": True,
                        },
                        {
                            "id": "alarmInstructions",
                            "label": "Alarm code / instructions",
                            "type": "textarea",
                            "placeholder": "Alarm code and disarm/arm instructions",
                            "required": False,
                            "conditionalOn": {"fieldId": "alarmSystem", "value": "Yes"},
                        },
                        {
                            "id": "parkingNotes",
                            "label": "Parking instructions",
                            "type": "textarea",
                            "placeholder": "Where should cleaning staff park? Any parking passes needed?",
                            "required": False,
                        },
                        {
                            "id": "specialInstructions",
                            "label": "Additional instructions",
                            "type": "textarea",
                            "placeholder": "Any other important details, compliance requirements, or special considerations",
                            "required": False,
                            "maxLength": 1000,
                        },
                    ],
                },
                {
                    "id": "commercial-context",
                    "title": "Contract Information",
                    "description": "Help us structure your service agreement.",
                    "fields": [
                        {
                            "id": "hasCurrentProvider",
                            "label": "Do you currently have a cleaning provider?",
                            "type": "radio",
                            "options": ["Yes", "No"],
                            "required": True,
                        },
                        {
                            "id": "currentContractExpires",
                            "label": "Current contract expiration date",
                            "type": "date",
                            "required": False,
                            "conditionalOn": {
                                "fieldId": "hasCurrentProvider",
                                "value": "Yes",
                            },
                            "hint": "This helps us plan the transition timeline",
                        },
                        {
                            "id": "preferredTerm",
                            "label": "Preferred contract term",
                            "type": "select",
                            "options": [
                                "Month-to-month",
                                "6 months",
                                "12 months",
                                "24 months",
                                "Custom term",
                            ],
                            "required": True,
                        },
                        {
                            "id": "isPartOfGroup",
                            "label": "Is this part of a multi-location practice?",
                            "type": "radio",
                            "options": ["Yes", "No"],
                            "required": True,
                        },
                        {
                            "id": "numberOfLocations",
                            "label": "Number of locations",
                            "type": "number",
                            "placeholder": "3",
                            "required": False,
                            "conditionalOn": {"fieldId": "isPartOfGroup", "value": "Yes"},
                        },
                    ],
                },
                {
                    "id": "media-uploads",
                    "title": "Facility Photos",
                    "description": "Photos help us provide accurate quotes (optional but recommended).",
                    "fields": [
                        {
                            "id": "propertyShots",
                            "label": "Facility photos",
                            "type": "file",
                            "accept": "image/*",
                            "required": False,
                            "multiple": True,
                            "maxFiles": 10,
                            "uploadMode": "client-r2",
                            "hint": "Upload photos of exam rooms, waiting areas, and other spaces to be cleaned",
                        },
                    ],
                },
            ]
        },
    }
